# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import l3_attackmitigator_pb2 as l3__attackmitigator__pb2


class L3AttackmitigatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOutput = channel.stream_unary(
                '/L3Attackmitigator/SendOutput',
                request_serializer=l3__attackmitigator__pb2.Output.SerializeToString,
                response_deserializer=l3__attackmitigator__pb2.EmptyMitigator.FromString,
                )
        self.GetMitigation = channel.unary_unary(
                '/L3Attackmitigator/GetMitigation',
                request_serializer=l3__attackmitigator__pb2.EmptyMitigator.SerializeToString,
                response_deserializer=l3__attackmitigator__pb2.EmptyMitigator.FromString,
                )


class L3AttackmitigatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOutput(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMitigation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_L3AttackmitigatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOutput': grpc.stream_unary_rpc_method_handler(
                    servicer.SendOutput,
                    request_deserializer=l3__attackmitigator__pb2.Output.FromString,
                    response_serializer=l3__attackmitigator__pb2.EmptyMitigator.SerializeToString,
            ),
            'GetMitigation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMitigation,
                    request_deserializer=l3__attackmitigator__pb2.EmptyMitigator.FromString,
                    response_serializer=l3__attackmitigator__pb2.EmptyMitigator.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'L3Attackmitigator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class L3Attackmitigator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOutput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/L3Attackmitigator/SendOutput',
            l3__attackmitigator__pb2.Output.SerializeToString,
            l3__attackmitigator__pb2.EmptyMitigator.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMitigation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/L3Attackmitigator/GetMitigation',
            l3__attackmitigator__pb2.EmptyMitigator.SerializeToString,
            l3__attackmitigator__pb2.EmptyMitigator.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
