FROM python:3

RUN apt-get update && apt-get install -y \
	libpcap0.8-dev \
	libuv1-dev

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir grpcio grpcio-tools

RUN python3 -m pip install --upgrade pip setuptools wheel pip-tools

COPY requirements.in requirements.in
RUN pip-compile --output-file=requirements.txt requirements.in
RUN python3 -m pip install -r requirements.in

WORKDIR .
COPY . .

ENV TSTAT_NAME="tstat_DRv4"
ENV INTERFACE="enp0s25"
ENV TSTAT_PID="$TSTAT_NAME"
ENV TSTAT_DIR="/$TSTAT_NAME"

RUN chmod +x /entrypoint.sh
ENTRYPOINT "/entrypoint.sh"
